


Traceback (most recent call last):

  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap

    self.run()

  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/lib/python3.6/site-packages/clustercontroller/clustercontroller.py", line 342, in __init__

    if self.acquire_master_lock():

  File "/usr/lib/python3.6/site-packages/clustercontroller/clustercontroller.py", line 434, in acquire_master_lock

    if self.master_lock.acquire(blocking=False, lock_ttl=30):

  File "/usr/lib/python3.6/site-packages/etcd/lock.py", line 68, in acquire

    res = self.client.write(self.path, self.uuid, ttl=lock_ttl, append=True)

  File "/usr/lib/python3.6/site-packages/etcd/client.py", line 500, in write

    response = self.api_execute(path, method, params=params)

  File "/usr/lib/python3.6/site-packages/etcd/client.py", line 907, in wrapper

    return self._handle_server_response(response)

  File "/usr/lib/python3.6/site-packages/etcd/client.py", line 987, in _handle_server_response

    etcd.EtcdError.handle(r)

  File "/usr/lib/python3.6/site-packages/etcd/__init__.py", line 306, in handle

    raise exc(msg, payload)

etcd.EtcdException: Raft Internal Error : etcdserver: request timed out
